I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scenario/dls/dls_q66.rpy", line 12634, in script
    scene cg Fl_mi_gost with Fl_dissolve1_5
  File "game/scenario/dls/dls_q66.rpy", line 12634, in <module>
    scene cg Fl_mi_gost with Fl_dissolve1_5
NameError: name 'Fl_dissolve1_5' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/scenario/dls/dls_q66.rpy", line 12634, in script
    scene cg Fl_mi_gost with Fl_dissolve1_5
  File "renpy/ast.py", line 1439, in execute
    paired = renpy.python.py_eval(self.paired)
  File "renpy/python.py", line 2276, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "renpy/python.py", line 2269, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/scenario/dls/dls_q66.rpy", line 12634, in <module>
    scene cg Fl_mi_gost with Fl_dissolve1_5
NameError: name 'Fl_dissolve1_5' is not defined

Windows-10-10.0.26100
Ren'Py 7.4.11.2266
Following the light 1.3
Mon May 26 01:57:43 2025
